const store = require('./redux')
const tvShows = require('./redux/tvShows')
const movies = require('./redux/movies')

store.dispatch(movies.addMovie('Soul'))
store.dispatch(movies.addMovie('The Matrix'))
store.dispatch(movies.addMovie('Onward'))
store.dispatch(movies.deleteMovie('The Matrix'))
store.dispatch(movies.moviesViewAll())

store.dispatch(tvShows.addTvShow('The Bachelor'))
store.dispatch(tvShows.addTvShow('Shark Tank'))
store.dispatch(tvShows.addTvShow('General Hospital'))
store.dispatch(tvShows.deleteTvShow('The Bachelor'))
store.dispatch(tvShows.tvShowsViewAll())
